<?php

use Illuminate\Database\Seeder;

class CategoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $categories = collect($this->defaultCategories)->map(function ($category) {
            return [
                'user_id' => 1,
                'category_name' => $category['category_name'],
                'slug' => Str::slug($category['category_name']),
                'category_id' => $category['category_id'],
                'thumbnail_id' => $category['thumbnail_id'],
                'icon_class' => 'fa-circle',
                'step' => $category['step'],
                'status' => 2,
                'created_at' => now()->toDateTimeString(),
                'updated_at' => now()->toDateTimeString(),
            ];
        });

        \App\Category::insert($categories->toArray());
    }

    protected $defaultCategories = [
        [
            'category_name' => 'Development',
            'category_id' => 0,
            'step' => 0,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Business',
            'category_id' => 0,
            'step' => 0,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Finance & Accounting',
            'category_id' => 0,
            'step' => 0,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'IT & Software',
            'category_id' => 0,
            'step' => 0,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Office Productivity',
            'category_id' => 0,
            'step' => 0,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Personal Development',
            'category_id' => 0,
            'step' => 0,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Design',
            'category_id' => 0,
            'step' => 0,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Marketing',
            'category_id' => 0,
            'step' => 0,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'LifeStyle',
            'category_id' => 0,
            'step' => 0,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Photography',
            'category_id' => 0,
            'step' => 0,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Health & Fitness',
            'category_id' => 0,
            'step' => 0,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Music',
            'category_id' => 0,
            'step' => 0,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Teaching & Academics',
            'category_id' => 0,
            'step' => 0,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Web Development',
            'category_id' => 1,
            'step' => 1,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Data Science',
            'category_id' => 1,
            'step' => 1,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Mobile Apps',
            'category_id' => 1,
            'step' => 1,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],[
            'category_name' => 'Programming Languages',
            'category_id' => 1,
            'step' => 1,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Game Development',
            'category_id' => 1,
            'step' => 1,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Databases',
            'category_id' => 1,
            'step' => 1,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Software Testing',
            'category_id' => 1,
            'step' => 1,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Software Engineering',
            'category_id' => 1,
            'step' => 1,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Development Tools',
            'category_id' => 1,
            'step' => 1,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'E-Commerce',
            'category_id' => 1,
            'step' => 1,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Finance',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Entrepreneurship',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Management',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Sales',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Strategy',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Operations',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Project Management',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Business Law',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Data & Analytics',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Home Business',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Human Resources',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Industry',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Home Business',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Media',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Real Estate',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Other',
            'category_id' => 2,
            'step' => 2,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Accounting & Bookkeeping',
            'category_id' => 3,
            'step' => 3,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Compliance',
            'category_id' => 3,
            'step' => 3,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Cryptocurrency & Blockchain',
            'category_id' => 3,
            'step' => 3,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Economics',
            'category_id' => 3,
            'step' => 3,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Finance',
            'category_id' => 3,
            'step' => 3,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Finance Cert & Exam Prep',
            'category_id' => 3,
            'step' => 3,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Financial Modeling & Analysis',
            'category_id' => 3,
            'step' => 3,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Investing & Trading',
            'category_id' => 3,
            'step' => 3,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Money Management Tool',
            'category_id' => 3,
            'step' => 3,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Taxes',
            'category_id' => 3,
            'step' => 3,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Other Finance Economics',
            'category_id' => 3,
            'step' => 3,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'IT Certification',
            'category_id' => 4,
            'step' => 4,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Network & Security',
            'category_id' => 4,
            'step' => 4,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Hardware',
            'category_id' => 4,
            'step' => 4,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Operation Systems',
            'category_id' => 4,
            'step' => 4,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Other',
            'category_id' => 4,
            'step' => 4,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Microsoft',
            'category_id' => 5,
            'step' => 5,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Apple',
            'category_id' => 5,
            'step' => 5,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Google',
            'category_id' => 5,
            'step' => 5,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'SAP',
            'category_id' => 5,
            'step' => 5,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Oracle',
            'category_id' => 5,
            'step' => 5,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Other',
            'category_id' => 5,
            'step' => 5,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Personal Transformation',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Productivity',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Leadership',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Personal Finance',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Career Development',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Parenting & Relationships',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Happiness',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Religion & Spirituality',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Personal Br& Building',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Creativity',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Influence',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Self Esteem',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Stress Management',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Memory & Study Skills',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Motivation',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Other',
            'category_id' => 6,
            'step' => 6,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Web Design',
            'category_id' => 7,
            'step' => 7,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Graphic Design',
            'category_id' => 7,
            'step' => 7,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Design Tools',
            'category_id' => 7,
            'step' => 7,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'User Experience',
            'category_id' => 7,
            'step' => 7,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Game Design',
            'category_id' => 7,
            'step' => 7,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Design Thinking',
            'category_id' => 7,
            'step' => 7,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Other',
            'category_id' => 7,
            'step' => 7,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => '3D & Animation',
            'category_id' => 7,
            'step' => 7,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Fashion',
            'category_id' => 7,
            'step' => 7,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Architecture Design',
            'category_id' => 7,
            'step' => 7,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Interior Design',
            'category_id' => 7,
            'step' => 7,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Other',
            'category_id' => 7,
            'step' => 7,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Marketing',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Digital Marketing',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Search Engine Optimization',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Social Media Marketing',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Br&ing',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Marketing Fundamental',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Analytics & Automation',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Public Relation',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Advertising',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],

        [
            'category_name' => 'Video & Mobile Marketing',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Content Marketing',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Growth Hacking',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Affiliate Marketing',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Product Marketing',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Other',
            'category_id' => 8,
            'step' => 8,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Arts & Crafts',
            'category_id' => 9,
            'step' => 9,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Food & Beverage',
            'category_id' => 9,
            'step' => 9,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Beauty & Make up',
            'category_id' => 9,
            'step' => 9,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Travel',
            'category_id' => 9,
            'step' => 9,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Gaming',
            'category_id' => 9,
            'step' => 9,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Home Improvement',
            'category_id' => 9,
            'step' => 9,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Pet Care & Training',
            'category_id' => 9,
            'step' => 9,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Other',
            'category_id' => 9,
            'step' => 9,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Digital Photography',
            'category_id' => 10,
            'step' => 10,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Photography Fundamental',
            'category_id' => 10,
            'step' => 10,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Portrait',
            'category_id' => 10,
            'step' => 10,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Photography Tools',
            'category_id' => 10,
            'step' => 10,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Commercial Photography',
            'category_id' => 10,
            'step' => 10,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Video Design',
            'category_id' => 10,
            'step' => 10,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Other',
            'category_id' => 10,
            'step' => 10,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Fitness',
            'category_id' => 11,
            'step' => 11,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'General Health',
            'category_id' => 11,
            'step' => 11,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Sports',
            'category_id' => 11,
            'step' => 11,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Nutrition',
            'category_id' => 11,
            'step' => 11,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Yoga',
            'category_id' => 11,
            'step' => 11,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Mental Health',
            'category_id' => 11,
            'step' => 11,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Dieting',
            'category_id' => 11,
            'step' => 11,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Self Defense',
            'category_id' => 11,
            'step' => 11,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Safety & First Aid',
            'category_id' => 11,
            'step' => 11,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Dance',
            'category_id' => 11,
            'step' => 11,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Mediation',
            'category_id' => 11,
            'step' => 11,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Other',
            'category_id' => 11,
            'step' => 11,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Instruments',
            'category_id' => 12,
            'step' => 12,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Production',
            'category_id' => 12,
            'step' => 12,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Music Fundamental',
            'category_id' => 12,
            'step' => 12,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Vocal',
            'category_id' => 12,
            'step' => 12,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Music Techniques',
            'category_id' => 12,
            'step' => 12,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Music Software',
            'category_id' => 12,
            'step' => 12,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Other',
            'category_id' => 12,
            'step' => 12,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Engineering',
            'category_id' => 13,
            'step' => 13,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Humanities',
            'category_id' => 13,
            'step' => 13,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Math',
            'category_id' => 13,
            'step' => 13,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Science',
            'category_id' => 13,
            'step' => 13,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Online Education',
            'category_id' => 13,
            'step' => 13,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Social Science',
            'category_id' => 13,
            'step' => 13,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Language',
            'category_id' => 13,
            'step' => 13,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Teacher Training',
            'category_id' => 13,
            'step' => 13,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Test Prep',
            'category_id' => 13,
            'step' => 13,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Other Teaching & Academics',
            'category_id' => 13,
            'step' => 13,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Javascript',
            'category_id' => 14,
            'step' => 14,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'React',
            'category_id' => 14,
            'step' => 14,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Angular',
            'category_id' => 14,
            'step' => 14,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'CSS',
            'category_id' => 14,
            'step' => 14,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'PHP',
            'category_id' => 14,
            'step' => 14,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'NodeJs',
            'category_id' => 14,
            'step' => 14,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Python',
            'category_id' => 14,
            'step' => 14,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Wordpress',
            'category_id' => 14,
            'step' => 14,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Laravel',
            'category_id' => 14,
            'step' => 14,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'O2system',
            'category_id' => 14,
            'step' => 14,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Codeigniter',
            'category_id' => 14,
            'step' => 14,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'YII2',
            'category_id' => 14,
            'step' => 14,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Google Flutter',
            'category_id' => 15,
            'step' => 15,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Android Development',
            'category_id' => 15,
            'step' => 15,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'IOS Development',
            'category_id' => 15,
            'step' => 15,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Swift',
            'category_id' => 15,
            'step' => 15,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'React Native',
            'category_id' => 15,
            'step' => 15,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Dart Programing Language',
            'category_id' => 15,
            'step' => 15,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Mobile Development',
            'category_id' => 15,
            'step' => 15,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Kotlin',
            'category_id' => 15,
            'step' => 15,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
        [
            'category_name' => 'Redux Framework',
            'category_id' => 15,
            'step' => 15,
            'thumbnail_id' => 1,
            'icon_class' => 'fa-circle',
        ],
    ];
}
